export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE";

export const CHECK_LOCAL_STORAGE_STATE = "CHECK_LOCAL_STORAGE_STATE";

export const DELETE_STUDENTS_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENTS_FAILURE = "DELETE_STUDENT_FAILURE";

export const GET_STUDENT_DETAILS_REQUEST = "GET_STUDENT_DETAILS_REQUEST";
export const GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS";
export const GET_STUDENT_DETAILS_FAILURE = "GET_STUDENT_DETAILS_FAILURE";

